# action.yml
name: "Push and Publish to MDF"
description: "Push Data to Staging area and publish the public URL to MDF"
inputs:
  globus_auth_client_id:
    description: "Globus Auth Application Client ID"
    required: true
  globus_auth_secret:
    description: "Globus Auth Application Secret"
    required: true

  mdf_source_id:
    description: "Source ID for Dataset in Materials Data Facility"
  mdf_title:
    description: "Dataset Title to Submit"
    required: true
  mdf_authors:
    description: "Dataset Authors"
    required: true
  mdf_affiliations:
    description: "Dataset Author Organization Affiliations"
    required: true
  mdf_publication_year:
    description: "Dataset Publication Year"
    required: true

  paths_to_publish:
    description: "File Paths to Publish"
    required: true

  is_test:
    description: "Is this a test submission?"
    default: false
    required: false
    type: boolean

  staging_object_store_url:
    description: "Staging Object Store URL"
    required: true
  aws_access_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_secret_access_key:
    description: "AWS Secrey Access Key"
    required: true
  s3_bucket_id:
    description: "S3 bucket ID"
    required: true
  s3_bucket_path:
    description: "S3 Bucket Path"
    required: true
outputs:
  logs:
    description: "Logs on processing"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.globus_auth_client_id }}
    - ${{ inputs.globus_auth_secret }}
    - ${{ inputs.mdf_source_id }}
    - ${{ inputs.mdf_title }}
    - ${{ inputs.mdf_authors }}
    - ${{ inputs.mdf_affiliations }}
    - ${{ inputs.mdf_publication_year }}
    - ${{ inputs.paths_to_publish }}
    - ${{ inputs.is_test }}
    - ${{ inputs.staging_object_store_url }}
    - ${{ inputs.aws_access_key_id }}
    - ${{ inputs.aws_secret_access_key }}
    - ${{ inputs.s3_bucket_id }}
    - ${{ inputs.s3_bucket_path }}
